// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6HH3AwrXVLQIfSfzR2qj5S82G-VVmLx4',
    appId: '1:148923600057:web:41b4dcd6badf4382b49f68',
    messagingSenderId: '148923600057',
    projectId: 'parllel-brains',
    authDomain: 'parllel-brains.firebaseapp.com',
    storageBucket: 'parllel-brains.firebasestorage.app',
    measurementId: 'G-8HCJRVB6NE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2_IXetAe7gG9LiHF7L9WHBgeR_M-iV98',
    appId: '1:148923600057:android:87ba11c5c7550297b49f68',
    messagingSenderId: '148923600057',
    projectId: 'parllel-brains',
    storageBucket: 'parllel-brains.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS10QQJ5NmCieTRE3q9BTFDDl8cX9wjIs',
    appId: '1:148923600057:ios:7713f593f3e1ac7db49f68',
    messagingSenderId: '148923600057',
    projectId: 'parllel-brains',
    storageBucket: 'parllel-brains.firebasestorage.app',
    iosBundleId: 'com.aditya.fintech.fintech',
  );
}
